[build]
  command = "npm ci && npm run build && npm run build:serverless"
  functions = "dist/functions"
  publish = "dist"

[[headers]]
  for = "/*"

  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''